# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
