# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=30000),
        ),
    ]
