# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yawlih', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-name_en']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='name_cn',
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
