# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yawlih', '0002_auto_20170612_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
