# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('yawlih', '0003_job_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(max_length=500)),
                ('amount_rmb', models.DecimalField(decimal_places=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yawlih.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=300)),
                ('name_cn', models.CharField(max_length=300)),
                ('website', models.URLField(max_length=500)),
                ('intro_en', models.TextField(blank=True, null=True)),
                ('intro_cn', models.TextField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='news',
            name='headline',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='investment',
            name='investors',
            field=models.ManyToManyField(blank=True, to='yawlih.Investor'),
        ),
    ]
