# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yawlih', '0004_auto_20170612_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='headline',
            field=models.CharField(default='', max_length=500),
        ),
    ]
