# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yawlih', '0005_investment_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
