# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yawlih', '0006_investment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
