# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yawlih', '0007_investment_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
