# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yawlih', '0008_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='link',
            field=models.URLField(default='', max_length=500),
        ),
    ]
