# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readinglist', '0003_remove_readingmaterial_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingmaterial',
            name='tags',
        ),
    ]
