# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 14:55
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('readinglist', '0005_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='tags',
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
