# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playquest', '0002_auto_20170730_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_saved',
            field=models.BooleanField(default=False),
        ),
    ]
