# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-30 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtest', '0002_auto_20170730_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashitem',
            old_name='game_owner',
            new_name='item_owner',
        ),
    ]
