# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
