# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_guestbook_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
