# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_guestbook_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteremails',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
    ]
