# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newsletteremails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
