# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170415_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbook',
            options={'ordering': ['-date_created']},
        ),
    ]
