# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 23:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
