# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srgraph', '0002_auto_20170513_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
