# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srgraph', '0003_auto_20170513_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('s1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s1', to='srgraph.Subreddit')),
                ('s2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2', to='srgraph.Subreddit')),
            ],
        ),
    ]
