# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srgraph', '0004_searchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
