# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srgraph', '0005_searchresult_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='s1',
            new_name='s_one',
        ),
        migrations.RenameField(
            model_name='searchresult',
            old_name='s2',
            new_name='s_two',
        ),
    ]
