# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srgraph', '0007_searchresult_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ['-updated']},
        ),
    ]
