# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srgraph', '0009_searchresult_last_searched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ['-last_searched']},
        ),
    ]
